# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46dfabf1cc43eb6d6abd45233715d47405c3cb7f59c7b38001771b4d728afb31418405b3e7c3c5dccfa92c6cc86c9659f565892647372c5ee0f68afc7fb05173

test:
  secret_key_base: 6d96af8a91fe6ea897f17da5a6be69b50b15421632ada2605cda2619f48e6c82b90f81d16fbdf04fc766317d455c9e360555d6316b230b66e6168b9fc47b6772

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
